[package]
name = "cutter"
version = "0.3.0"
authors = ["Håkon Solbjørg <hlsolbjorg@gmail.com>"]
edition = "2018"

[[bin]]
path = "src/main.rs"
name = "cutter"

[dependencies]
clap = "2.33.0"
raster = "*"
rust-s3 = "0.12.1"
serde = { version = "1.0", features = ["derive"] }
